#SPDX-License-Identifier: MIT-0
---
# tasks file for webserver
- name : install package
  package :
    name: "{{package}}"
    state: present

- name : copy html file
  copy :
    src : index.html
    dest : /var/www/html/index.html
  notify : 
    - start service